
services:
  build-one-php:
    build: .
    container_name: ossd-5-mylocation
    ports:
      - "1305:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
